//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 11:29:24 AM PDT 
//


package com.prairiesky.transform.cobieifc.settings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AttributeSettingsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AttributeSettingsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{settings.cobieifc.transform.prairiesky.com}AttributeCountDefaultUnit"/>
 *         &lt;element ref="{settings.cobieifc.transform.prairiesky.com}FacilityAttributeCategory"/>
 *         &lt;element ref="{settings.cobieifc.transform.prairiesky.com}FloorAttributeCategory"/>
 *         &lt;element ref="{settings.cobieifc.transform.prairiesky.com}SpaceAttributeCategory"/>
 *         &lt;element ref="{settings.cobieifc.transform.prairiesky.com}TypeAttributeCategory"/>
 *         &lt;element ref="{settings.cobieifc.transform.prairiesky.com}ComponentAttributeCategory"/>
 *         &lt;element ref="{settings.cobieifc.transform.prairiesky.com}PropertyExclusions" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AttributeSettingsType", propOrder = {
    "attributeCountDefaultUnit",
    "facilityAttributeCategory",
    "floorAttributeCategory",
    "spaceAttributeCategory",
    "typeAttributeCategory",
    "componentAttributeCategory",
    "propertyExclusions"
})
public class AttributeSettingsType {

    @XmlElement(name = "AttributeCountDefaultUnit", required = true, defaultValue = "each")
    protected String attributeCountDefaultUnit;
    @XmlElement(name = "FacilityAttributeCategory", required = true, defaultValue = "Requirement")
    protected String facilityAttributeCategory;
    @XmlElement(name = "FloorAttributeCategory", required = true, defaultValue = "Requirement")
    protected String floorAttributeCategory;
    @XmlElement(name = "SpaceAttributeCategory", required = true, defaultValue = "Requirement")
    protected String spaceAttributeCategory;
    @XmlElement(name = "TypeAttributeCategory", required = true, defaultValue = "Requirement")
    protected String typeAttributeCategory;
    @XmlElement(name = "ComponentAttributeCategory", required = true, defaultValue = "Requirement")
    protected String componentAttributeCategory;
    @XmlElement(name = "PropertyExclusions")
    protected PropertyExclusionsType propertyExclusions;

    /**
     * Gets the value of the attributeCountDefaultUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttributeCountDefaultUnit() {
        return attributeCountDefaultUnit;
    }

    /**
     * Sets the value of the attributeCountDefaultUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttributeCountDefaultUnit(String value) {
        this.attributeCountDefaultUnit = value;
    }

    /**
     * Gets the value of the facilityAttributeCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFacilityAttributeCategory() {
        return facilityAttributeCategory;
    }

    /**
     * Sets the value of the facilityAttributeCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFacilityAttributeCategory(String value) {
        this.facilityAttributeCategory = value;
    }

    /**
     * Gets the value of the floorAttributeCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFloorAttributeCategory() {
        return floorAttributeCategory;
    }

    /**
     * Sets the value of the floorAttributeCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFloorAttributeCategory(String value) {
        this.floorAttributeCategory = value;
    }

    /**
     * Gets the value of the spaceAttributeCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpaceAttributeCategory() {
        return spaceAttributeCategory;
    }

    /**
     * Sets the value of the spaceAttributeCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpaceAttributeCategory(String value) {
        this.spaceAttributeCategory = value;
    }

    /**
     * Gets the value of the typeAttributeCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeAttributeCategory() {
        return typeAttributeCategory;
    }

    /**
     * Sets the value of the typeAttributeCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeAttributeCategory(String value) {
        this.typeAttributeCategory = value;
    }

    /**
     * Gets the value of the componentAttributeCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComponentAttributeCategory() {
        return componentAttributeCategory;
    }

    /**
     * Sets the value of the componentAttributeCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComponentAttributeCategory(String value) {
        this.componentAttributeCategory = value;
    }

    /**
     * Gets the value of the propertyExclusions property.
     * 
     * @return
     *     possible object is
     *     {@link PropertyExclusionsType }
     *     
     */
    public PropertyExclusionsType getPropertyExclusions() {
        return propertyExclusions;
    }

    /**
     * Sets the value of the propertyExclusions property.
     * 
     * @param value
     *     allowed object is
     *     {@link PropertyExclusionsType }
     *     
     */
    public void setPropertyExclusions(PropertyExclusionsType value) {
        this.propertyExclusions = value;
    }

}
