//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 11:29:24 AM PDT 
//


package com.prairiesky.transform.cobieifc.settings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FloorSettingsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FloorSettingsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{settings.cobieifc.transform.prairiesky.com}FloorHeightPropertyNames"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FloorSettingsType", propOrder = {
    "floorHeightPropertyNames"
})
public class FloorSettingsType {

    @XmlElement(name = "FloorHeightPropertyNames", required = true)
    protected NameCollectionType floorHeightPropertyNames;

    /**
     * Gets the value of the floorHeightPropertyNames property.
     * 
     * @return
     *     possible object is
     *     {@link NameCollectionType }
     *     
     */
    public NameCollectionType getFloorHeightPropertyNames() {
        return floorHeightPropertyNames;
    }

    /**
     * Sets the value of the floorHeightPropertyNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameCollectionType }
     *     
     */
    public void setFloorHeightPropertyNames(NameCollectionType value) {
        this.floorHeightPropertyNames = value;
    }

}
