//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 11:29:24 AM PDT 
//


package com.prairiesky.transform.cobieifc.settings;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.prairiesky.transform.cobieifc.settings package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ConstituentsPropertyNames_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "ConstituentsPropertyNames");
    private final static QName _ModelNumberPropertyNames_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "ModelNumberPropertyNames");
    private final static QName _SpaceAttributeCategory_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "SpaceAttributeCategory");
    private final static QName _DocumentSettings_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "DocumentSettings");
    private final static QName _AssetTypePropertyNames_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "AssetTypePropertyNames");
    private final static QName _TypePropertyNameExclusions_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "TypePropertyNameExclusions");
    private final static QName _ValueExclusions_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "ValueExclusions");
    private final static QName _ExpectedLifePropertyNames_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "ExpectedLifePropertyNames");
    private final static QName _SustainabilityPerformancePropertyNames_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "SustainabilityPerformancePropertyNames");
    private final static QName _ComponentAttributeCategory_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "ComponentAttributeCategory");
    private final static QName _FacilityPropertySetNameExclusions_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "FacilityPropertySetNameExclusions");
    private final static QName _TypePropertySetNameExclusions_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "TypePropertySetNameExclusions");
    private final static QName _FrequencyPropertyNames_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "FrequencyPropertyNames");
    private final static QName _IfcProductExclusions_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "IfcProductExclusions");
    private final static QName _ReplacementCostPropertyNames_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "ReplacementCostPropertyNames");
    private final static QName _ComponentPropertyNameExclusions_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "ComponentPropertyNameExclusions");
    private final static QName _WarrantyDurationPartsPropertyNames_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "WarrantyDurationPartsPropertyNames");
    private final static QName _FacilitySiteDefaultName_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "FacilitySiteDefaultName");
    private final static QName _FloorSettings_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "FloorSettings");
    private final static QName _Name_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "Name");
    private final static QName _SizePropertyNames_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "SizePropertyNames");
    private final static QName _NominalHeightPropertyNames_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "NominalHeightPropertyNames");
    private final static QName _WarrantyGuarantorPartsPropertyNames_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "WarrantyGuarantorPartsPropertyNames");
    private final static QName _SetNumberPropertyNames_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "SetNumberPropertyNames");
    private final static QName _ShapePropertyNames_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "ShapePropertyNames");
    private final static QName _FacilityPropertyNameExclusions_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "FacilityPropertyNameExclusions");
    private final static QName _GradePropertyNames_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "GradePropertyNames");
    private final static QName _NameEqValueExceptions_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "NameEqValueExceptions");
    private final static QName _DefaultWarrantyDurationUnit_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "DefaultWarrantyDurationUnit");
    private final static QName _PartNumberPropertyNames_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "PartNumberPropertyNames");
    private final static QName _FacilityAttributeCategory_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "FacilityAttributeCategory");
    private final static QName _ManufacturerPropertyNames_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "ManufacturerPropertyNames");
    private final static QName _CodePerformancePropertyNames_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "CodePerformancePropertyNames");
    private final static QName _Settings_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "Settings");
    private final static QName _ModelReferencePropertyNames_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "ModelReferencePropertyNames");
    private final static QName _TypeAttributeCategory_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "TypeAttributeCategory");
    private final static QName _ExcludePropertiesOnNameEqValue_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "ExcludePropertiesOnNameEqValue");
    private final static QName _FloorPropertyNameExclusions_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "FloorPropertyNameExclusions");
    private final static QName _SpareSettings_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "SpareSettings");
    private final static QName _WarrantyDescriptionPropertyNames_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "WarrantyDescriptionPropertyNames");
    private final static QName _FloorHeightPropertyNames_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "FloorHeightPropertyNames");
    private final static QName _PropertyExclusions_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "PropertyExclusions");
    private final static QName _FeaturesPropertyNames_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "FeaturesPropertyNames");
    private final static QName _AttributeSettings_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "AttributeSettings");
    private final static QName _AccessibilityPerformancePropertyNames_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "AccessibilityPerformancePropertyNames");
    private final static QName _JobSettings_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "JobSettings");
    private final static QName _TypeSettings_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "TypeSettings");
    private final static QName _IfcTypeExclusions_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "IfcTypeExclusions");
    private final static QName _AttributeCountDefaultUnit_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "AttributeCountDefaultUnit");
    private final static QName _StartPropertyNames_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "StartPropertyNames");
    private final static QName _FinishPropertyNames_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "FinishPropertyNames");
    private final static QName _WarrantyGuarantorLaborPropertyNames_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "WarrantyGuarantorLaborPropertyNames");
    private final static QName _FloorPropertySetNameExclusions_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "FloorPropertySetNameExclusions");
    private final static QName _SpacePropertySetNameExclusions_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "SpacePropertySetNameExclusions");
    private final static QName _GlobalPropertyNameExclusions_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "GlobalPropertyNameExclusions");
    private final static QName _SupplierPropertyNames_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "SupplierPropertyNames");
    private final static QName _MaterialPropertyNames_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "MaterialPropertyNames");
    private final static QName _NominalWidthPropertyNames_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "NominalWidthPropertyNames");
    private final static QName _SpacePropertyNameExclusions_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "SpacePropertyNameExclusions");
    private final static QName _NominalLengthPropertyNames_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "NominalLengthPropertyNames");
    private final static QName _GlobalPropertySetNameExclusions_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "GlobalPropertySetNameExclusions");
    private final static QName _DurationPropertyNames_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "DurationPropertyNames");
    private final static QName _FloorAttributeCategory_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "FloorAttributeCategory");
    private final static QName _Exclude_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "Exclude");
    private final static QName _FacilitySettings_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "FacilitySettings");
    private final static QName _FacilityDefaultProjectName_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "FacilityDefaultProjectName");
    private final static QName _GeneratePlaceholderTypeDocuments_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "GeneratePlaceholderTypeDocuments");
    private final static QName _WarrantyDurationLaborPropertyNames_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "WarrantyDurationLaborPropertyNames");
    private final static QName _ComponentPropertySetNameExclusions_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "ComponentPropertySetNameExclusions");
    private final static QName _ColorPropertyNames_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "ColorPropertyNames");
    private final static QName _ComponentSettings_QNAME = new QName("settings.cobieifc.transform.prairiesky.com", "ComponentSettings");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.prairiesky.transform.cobieifc.settings
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NameCollectionType }
     * 
     */
    public NameCollectionType createNameCollectionType() {
        return new NameCollectionType();
    }

    /**
     * Create an instance of {@link ValueExclusionCollectionType }
     * 
     */
    public ValueExclusionCollectionType createValueExclusionCollectionType() {
        return new ValueExclusionCollectionType();
    }

    /**
     * Create an instance of {@link PropertyExclusionsType }
     * 
     */
    public PropertyExclusionsType createPropertyExclusionsType() {
        return new PropertyExclusionsType();
    }

    /**
     * Create an instance of {@link SpareSettingsType }
     * 
     */
    public SpareSettingsType createSpareSettingsType() {
        return new SpareSettingsType();
    }

    /**
     * Create an instance of {@link SettingsType }
     * 
     */
    public SettingsType createSettingsType() {
        return new SettingsType();
    }

    /**
     * Create an instance of {@link DocumentSettingsType }
     * 
     */
    public DocumentSettingsType createDocumentSettingsType() {
        return new DocumentSettingsType();
    }

    /**
     * Create an instance of {@link FloorSettingsType }
     * 
     */
    public FloorSettingsType createFloorSettingsType() {
        return new FloorSettingsType();
    }

    /**
     * Create an instance of {@link FacilitySettingsType }
     * 
     */
    public FacilitySettingsType createFacilitySettingsType() {
        return new FacilitySettingsType();
    }

    /**
     * Create an instance of {@link PropertyExclusionType }
     * 
     */
    public PropertyExclusionType createPropertyExclusionType() {
        return new PropertyExclusionType();
    }

    /**
     * Create an instance of {@link ComponentSettingsType }
     * 
     */
    public ComponentSettingsType createComponentSettingsType() {
        return new ComponentSettingsType();
    }

    /**
     * Create an instance of {@link JobSettingsType }
     * 
     */
    public JobSettingsType createJobSettingsType() {
        return new JobSettingsType();
    }

    /**
     * Create an instance of {@link AttributeSettingsType }
     * 
     */
    public AttributeSettingsType createAttributeSettingsType() {
        return new AttributeSettingsType();
    }

    /**
     * Create an instance of {@link TypeSettingsType }
     * 
     */
    public TypeSettingsType createTypeSettingsType() {
        return new TypeSettingsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "ConstituentsPropertyNames")
    public JAXBElement<NameCollectionType> createConstituentsPropertyNames(NameCollectionType value) {
        return new JAXBElement<NameCollectionType>(_ConstituentsPropertyNames_QNAME, NameCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "ModelNumberPropertyNames")
    public JAXBElement<NameCollectionType> createModelNumberPropertyNames(NameCollectionType value) {
        return new JAXBElement<NameCollectionType>(_ModelNumberPropertyNames_QNAME, NameCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "SpaceAttributeCategory", defaultValue = "Requirement")
    public JAXBElement<String> createSpaceAttributeCategory(String value) {
        return new JAXBElement<String>(_SpaceAttributeCategory_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DocumentSettingsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "DocumentSettings")
    public JAXBElement<DocumentSettingsType> createDocumentSettings(DocumentSettingsType value) {
        return new JAXBElement<DocumentSettingsType>(_DocumentSettings_QNAME, DocumentSettingsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "AssetTypePropertyNames")
    public JAXBElement<NameCollectionType> createAssetTypePropertyNames(NameCollectionType value) {
        return new JAXBElement<NameCollectionType>(_AssetTypePropertyNames_QNAME, NameCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValueExclusionCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "TypePropertyNameExclusions")
    public JAXBElement<ValueExclusionCollectionType> createTypePropertyNameExclusions(ValueExclusionCollectionType value) {
        return new JAXBElement<ValueExclusionCollectionType>(_TypePropertyNameExclusions_QNAME, ValueExclusionCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValueExclusionCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "ValueExclusions")
    public JAXBElement<ValueExclusionCollectionType> createValueExclusions(ValueExclusionCollectionType value) {
        return new JAXBElement<ValueExclusionCollectionType>(_ValueExclusions_QNAME, ValueExclusionCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "ExpectedLifePropertyNames")
    public JAXBElement<NameCollectionType> createExpectedLifePropertyNames(NameCollectionType value) {
        return new JAXBElement<NameCollectionType>(_ExpectedLifePropertyNames_QNAME, NameCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "SustainabilityPerformancePropertyNames")
    public JAXBElement<NameCollectionType> createSustainabilityPerformancePropertyNames(NameCollectionType value) {
        return new JAXBElement<NameCollectionType>(_SustainabilityPerformancePropertyNames_QNAME, NameCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "ComponentAttributeCategory", defaultValue = "Requirement")
    public JAXBElement<String> createComponentAttributeCategory(String value) {
        return new JAXBElement<String>(_ComponentAttributeCategory_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValueExclusionCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "FacilityPropertySetNameExclusions")
    public JAXBElement<ValueExclusionCollectionType> createFacilityPropertySetNameExclusions(ValueExclusionCollectionType value) {
        return new JAXBElement<ValueExclusionCollectionType>(_FacilityPropertySetNameExclusions_QNAME, ValueExclusionCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValueExclusionCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "TypePropertySetNameExclusions")
    public JAXBElement<ValueExclusionCollectionType> createTypePropertySetNameExclusions(ValueExclusionCollectionType value) {
        return new JAXBElement<ValueExclusionCollectionType>(_TypePropertySetNameExclusions_QNAME, ValueExclusionCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "FrequencyPropertyNames")
    public JAXBElement<NameCollectionType> createFrequencyPropertyNames(NameCollectionType value) {
        return new JAXBElement<NameCollectionType>(_FrequencyPropertyNames_QNAME, NameCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "IfcProductExclusions")
    public JAXBElement<NameCollectionType> createIfcProductExclusions(NameCollectionType value) {
        return new JAXBElement<NameCollectionType>(_IfcProductExclusions_QNAME, NameCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "ReplacementCostPropertyNames")
    public JAXBElement<NameCollectionType> createReplacementCostPropertyNames(NameCollectionType value) {
        return new JAXBElement<NameCollectionType>(_ReplacementCostPropertyNames_QNAME, NameCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValueExclusionCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "ComponentPropertyNameExclusions")
    public JAXBElement<ValueExclusionCollectionType> createComponentPropertyNameExclusions(ValueExclusionCollectionType value) {
        return new JAXBElement<ValueExclusionCollectionType>(_ComponentPropertyNameExclusions_QNAME, ValueExclusionCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "WarrantyDurationPartsPropertyNames")
    public JAXBElement<NameCollectionType> createWarrantyDurationPartsPropertyNames(NameCollectionType value) {
        return new JAXBElement<NameCollectionType>(_WarrantyDurationPartsPropertyNames_QNAME, NameCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "FacilitySiteDefaultName", defaultValue = "Default Site")
    public JAXBElement<String> createFacilitySiteDefaultName(String value) {
        return new JAXBElement<String>(_FacilitySiteDefaultName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FloorSettingsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "FloorSettings")
    public JAXBElement<FloorSettingsType> createFloorSettings(FloorSettingsType value) {
        return new JAXBElement<FloorSettingsType>(_FloorSettings_QNAME, FloorSettingsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "Name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "SizePropertyNames")
    public JAXBElement<NameCollectionType> createSizePropertyNames(NameCollectionType value) {
        return new JAXBElement<NameCollectionType>(_SizePropertyNames_QNAME, NameCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "NominalHeightPropertyNames")
    public JAXBElement<NameCollectionType> createNominalHeightPropertyNames(NameCollectionType value) {
        return new JAXBElement<NameCollectionType>(_NominalHeightPropertyNames_QNAME, NameCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "WarrantyGuarantorPartsPropertyNames")
    public JAXBElement<NameCollectionType> createWarrantyGuarantorPartsPropertyNames(NameCollectionType value) {
        return new JAXBElement<NameCollectionType>(_WarrantyGuarantorPartsPropertyNames_QNAME, NameCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "SetNumberPropertyNames")
    public JAXBElement<NameCollectionType> createSetNumberPropertyNames(NameCollectionType value) {
        return new JAXBElement<NameCollectionType>(_SetNumberPropertyNames_QNAME, NameCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "ShapePropertyNames")
    public JAXBElement<NameCollectionType> createShapePropertyNames(NameCollectionType value) {
        return new JAXBElement<NameCollectionType>(_ShapePropertyNames_QNAME, NameCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValueExclusionCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "FacilityPropertyNameExclusions")
    public JAXBElement<ValueExclusionCollectionType> createFacilityPropertyNameExclusions(ValueExclusionCollectionType value) {
        return new JAXBElement<ValueExclusionCollectionType>(_FacilityPropertyNameExclusions_QNAME, ValueExclusionCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "GradePropertyNames")
    public JAXBElement<NameCollectionType> createGradePropertyNames(NameCollectionType value) {
        return new JAXBElement<NameCollectionType>(_GradePropertyNames_QNAME, NameCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "NameEqValueExceptions")
    public JAXBElement<NameCollectionType> createNameEqValueExceptions(NameCollectionType value) {
        return new JAXBElement<NameCollectionType>(_NameEqValueExceptions_QNAME, NameCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "DefaultWarrantyDurationUnit")
    public JAXBElement<String> createDefaultWarrantyDurationUnit(String value) {
        return new JAXBElement<String>(_DefaultWarrantyDurationUnit_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "PartNumberPropertyNames")
    public JAXBElement<NameCollectionType> createPartNumberPropertyNames(NameCollectionType value) {
        return new JAXBElement<NameCollectionType>(_PartNumberPropertyNames_QNAME, NameCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "FacilityAttributeCategory", defaultValue = "Requirement")
    public JAXBElement<String> createFacilityAttributeCategory(String value) {
        return new JAXBElement<String>(_FacilityAttributeCategory_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "ManufacturerPropertyNames")
    public JAXBElement<NameCollectionType> createManufacturerPropertyNames(NameCollectionType value) {
        return new JAXBElement<NameCollectionType>(_ManufacturerPropertyNames_QNAME, NameCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "CodePerformancePropertyNames")
    public JAXBElement<NameCollectionType> createCodePerformancePropertyNames(NameCollectionType value) {
        return new JAXBElement<NameCollectionType>(_CodePerformancePropertyNames_QNAME, NameCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SettingsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "Settings")
    public JAXBElement<SettingsType> createSettings(SettingsType value) {
        return new JAXBElement<SettingsType>(_Settings_QNAME, SettingsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "ModelReferencePropertyNames")
    public JAXBElement<NameCollectionType> createModelReferencePropertyNames(NameCollectionType value) {
        return new JAXBElement<NameCollectionType>(_ModelReferencePropertyNames_QNAME, NameCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "TypeAttributeCategory", defaultValue = "Requirement")
    public JAXBElement<String> createTypeAttributeCategory(String value) {
        return new JAXBElement<String>(_TypeAttributeCategory_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "ExcludePropertiesOnNameEqValue")
    public JAXBElement<Boolean> createExcludePropertiesOnNameEqValue(Boolean value) {
        return new JAXBElement<Boolean>(_ExcludePropertiesOnNameEqValue_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValueExclusionCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "FloorPropertyNameExclusions")
    public JAXBElement<ValueExclusionCollectionType> createFloorPropertyNameExclusions(ValueExclusionCollectionType value) {
        return new JAXBElement<ValueExclusionCollectionType>(_FloorPropertyNameExclusions_QNAME, ValueExclusionCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpareSettingsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "SpareSettings")
    public JAXBElement<SpareSettingsType> createSpareSettings(SpareSettingsType value) {
        return new JAXBElement<SpareSettingsType>(_SpareSettings_QNAME, SpareSettingsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "WarrantyDescriptionPropertyNames")
    public JAXBElement<NameCollectionType> createWarrantyDescriptionPropertyNames(NameCollectionType value) {
        return new JAXBElement<NameCollectionType>(_WarrantyDescriptionPropertyNames_QNAME, NameCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "FloorHeightPropertyNames")
    public JAXBElement<NameCollectionType> createFloorHeightPropertyNames(NameCollectionType value) {
        return new JAXBElement<NameCollectionType>(_FloorHeightPropertyNames_QNAME, NameCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PropertyExclusionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "PropertyExclusions")
    public JAXBElement<PropertyExclusionsType> createPropertyExclusions(PropertyExclusionsType value) {
        return new JAXBElement<PropertyExclusionsType>(_PropertyExclusions_QNAME, PropertyExclusionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "FeaturesPropertyNames")
    public JAXBElement<NameCollectionType> createFeaturesPropertyNames(NameCollectionType value) {
        return new JAXBElement<NameCollectionType>(_FeaturesPropertyNames_QNAME, NameCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeSettingsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "AttributeSettings")
    public JAXBElement<AttributeSettingsType> createAttributeSettings(AttributeSettingsType value) {
        return new JAXBElement<AttributeSettingsType>(_AttributeSettings_QNAME, AttributeSettingsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "AccessibilityPerformancePropertyNames")
    public JAXBElement<NameCollectionType> createAccessibilityPerformancePropertyNames(NameCollectionType value) {
        return new JAXBElement<NameCollectionType>(_AccessibilityPerformancePropertyNames_QNAME, NameCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JobSettingsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "JobSettings")
    public JAXBElement<JobSettingsType> createJobSettings(JobSettingsType value) {
        return new JAXBElement<JobSettingsType>(_JobSettings_QNAME, JobSettingsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeSettingsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "TypeSettings")
    public JAXBElement<TypeSettingsType> createTypeSettings(TypeSettingsType value) {
        return new JAXBElement<TypeSettingsType>(_TypeSettings_QNAME, TypeSettingsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "IfcTypeExclusions")
    public JAXBElement<NameCollectionType> createIfcTypeExclusions(NameCollectionType value) {
        return new JAXBElement<NameCollectionType>(_IfcTypeExclusions_QNAME, NameCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "AttributeCountDefaultUnit", defaultValue = "each")
    public JAXBElement<String> createAttributeCountDefaultUnit(String value) {
        return new JAXBElement<String>(_AttributeCountDefaultUnit_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "StartPropertyNames")
    public JAXBElement<NameCollectionType> createStartPropertyNames(NameCollectionType value) {
        return new JAXBElement<NameCollectionType>(_StartPropertyNames_QNAME, NameCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "FinishPropertyNames")
    public JAXBElement<NameCollectionType> createFinishPropertyNames(NameCollectionType value) {
        return new JAXBElement<NameCollectionType>(_FinishPropertyNames_QNAME, NameCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "WarrantyGuarantorLaborPropertyNames")
    public JAXBElement<NameCollectionType> createWarrantyGuarantorLaborPropertyNames(NameCollectionType value) {
        return new JAXBElement<NameCollectionType>(_WarrantyGuarantorLaborPropertyNames_QNAME, NameCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValueExclusionCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "FloorPropertySetNameExclusions")
    public JAXBElement<ValueExclusionCollectionType> createFloorPropertySetNameExclusions(ValueExclusionCollectionType value) {
        return new JAXBElement<ValueExclusionCollectionType>(_FloorPropertySetNameExclusions_QNAME, ValueExclusionCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValueExclusionCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "SpacePropertySetNameExclusions")
    public JAXBElement<ValueExclusionCollectionType> createSpacePropertySetNameExclusions(ValueExclusionCollectionType value) {
        return new JAXBElement<ValueExclusionCollectionType>(_SpacePropertySetNameExclusions_QNAME, ValueExclusionCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValueExclusionCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "GlobalPropertyNameExclusions")
    public JAXBElement<ValueExclusionCollectionType> createGlobalPropertyNameExclusions(ValueExclusionCollectionType value) {
        return new JAXBElement<ValueExclusionCollectionType>(_GlobalPropertyNameExclusions_QNAME, ValueExclusionCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "SupplierPropertyNames")
    public JAXBElement<NameCollectionType> createSupplierPropertyNames(NameCollectionType value) {
        return new JAXBElement<NameCollectionType>(_SupplierPropertyNames_QNAME, NameCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "MaterialPropertyNames")
    public JAXBElement<NameCollectionType> createMaterialPropertyNames(NameCollectionType value) {
        return new JAXBElement<NameCollectionType>(_MaterialPropertyNames_QNAME, NameCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "NominalWidthPropertyNames")
    public JAXBElement<NameCollectionType> createNominalWidthPropertyNames(NameCollectionType value) {
        return new JAXBElement<NameCollectionType>(_NominalWidthPropertyNames_QNAME, NameCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValueExclusionCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "SpacePropertyNameExclusions")
    public JAXBElement<ValueExclusionCollectionType> createSpacePropertyNameExclusions(ValueExclusionCollectionType value) {
        return new JAXBElement<ValueExclusionCollectionType>(_SpacePropertyNameExclusions_QNAME, ValueExclusionCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "NominalLengthPropertyNames")
    public JAXBElement<NameCollectionType> createNominalLengthPropertyNames(NameCollectionType value) {
        return new JAXBElement<NameCollectionType>(_NominalLengthPropertyNames_QNAME, NameCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValueExclusionCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "GlobalPropertySetNameExclusions")
    public JAXBElement<ValueExclusionCollectionType> createGlobalPropertySetNameExclusions(ValueExclusionCollectionType value) {
        return new JAXBElement<ValueExclusionCollectionType>(_GlobalPropertySetNameExclusions_QNAME, ValueExclusionCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "DurationPropertyNames")
    public JAXBElement<NameCollectionType> createDurationPropertyNames(NameCollectionType value) {
        return new JAXBElement<NameCollectionType>(_DurationPropertyNames_QNAME, NameCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "FloorAttributeCategory", defaultValue = "Requirement")
    public JAXBElement<String> createFloorAttributeCategory(String value) {
        return new JAXBElement<String>(_FloorAttributeCategory_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PropertyExclusionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "Exclude")
    public JAXBElement<PropertyExclusionType> createExclude(PropertyExclusionType value) {
        return new JAXBElement<PropertyExclusionType>(_Exclude_QNAME, PropertyExclusionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FacilitySettingsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "FacilitySettings")
    public JAXBElement<FacilitySettingsType> createFacilitySettings(FacilitySettingsType value) {
        return new JAXBElement<FacilitySettingsType>(_FacilitySettings_QNAME, FacilitySettingsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "FacilityDefaultProjectName", defaultValue = "Default Project")
    public JAXBElement<String> createFacilityDefaultProjectName(String value) {
        return new JAXBElement<String>(_FacilityDefaultProjectName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "GeneratePlaceholderTypeDocuments")
    public JAXBElement<Boolean> createGeneratePlaceholderTypeDocuments(Boolean value) {
        return new JAXBElement<Boolean>(_GeneratePlaceholderTypeDocuments_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "WarrantyDurationLaborPropertyNames")
    public JAXBElement<NameCollectionType> createWarrantyDurationLaborPropertyNames(NameCollectionType value) {
        return new JAXBElement<NameCollectionType>(_WarrantyDurationLaborPropertyNames_QNAME, NameCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValueExclusionCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "ComponentPropertySetNameExclusions")
    public JAXBElement<ValueExclusionCollectionType> createComponentPropertySetNameExclusions(ValueExclusionCollectionType value) {
        return new JAXBElement<ValueExclusionCollectionType>(_ComponentPropertySetNameExclusions_QNAME, ValueExclusionCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "ColorPropertyNames")
    public JAXBElement<NameCollectionType> createColorPropertyNames(NameCollectionType value) {
        return new JAXBElement<NameCollectionType>(_ColorPropertyNames_QNAME, NameCollectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ComponentSettingsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "settings.cobieifc.transform.prairiesky.com", name = "ComponentSettings")
    public JAXBElement<ComponentSettingsType> createComponentSettings(ComponentSettingsType value) {
        return new JAXBElement<ComponentSettingsType>(_ComponentSettings_QNAME, ComponentSettingsType.class, null, value);
    }

}
