//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 11:29:24 AM PDT 
//


package com.prairiesky.transform.cobieifc.settings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PropertyExclusionsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PropertyExclusionsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{settings.cobieifc.transform.prairiesky.com}ExcludePropertiesOnNameEqValue"/>
 *         &lt;element ref="{settings.cobieifc.transform.prairiesky.com}NameEqValueExceptions" minOccurs="0"/>
 *         &lt;element ref="{settings.cobieifc.transform.prairiesky.com}ValueExclusions" minOccurs="0"/>
 *         &lt;element ref="{settings.cobieifc.transform.prairiesky.com}GlobalPropertySetNameExclusions" minOccurs="0"/>
 *         &lt;element ref="{settings.cobieifc.transform.prairiesky.com}GlobalPropertyNameExclusions" minOccurs="0"/>
 *         &lt;element ref="{settings.cobieifc.transform.prairiesky.com}FacilityPropertySetNameExclusions" minOccurs="0"/>
 *         &lt;element ref="{settings.cobieifc.transform.prairiesky.com}FacilityPropertyNameExclusions" minOccurs="0"/>
 *         &lt;element ref="{settings.cobieifc.transform.prairiesky.com}FloorPropertySetNameExclusions" minOccurs="0"/>
 *         &lt;element ref="{settings.cobieifc.transform.prairiesky.com}FloorPropertyNameExclusions" minOccurs="0"/>
 *         &lt;element ref="{settings.cobieifc.transform.prairiesky.com}SpacePropertySetNameExclusions" minOccurs="0"/>
 *         &lt;element ref="{settings.cobieifc.transform.prairiesky.com}SpacePropertyNameExclusions" minOccurs="0"/>
 *         &lt;element ref="{settings.cobieifc.transform.prairiesky.com}TypePropertySetNameExclusions" minOccurs="0"/>
 *         &lt;element ref="{settings.cobieifc.transform.prairiesky.com}TypePropertyNameExclusions" minOccurs="0"/>
 *         &lt;element ref="{settings.cobieifc.transform.prairiesky.com}ComponentPropertySetNameExclusions" minOccurs="0"/>
 *         &lt;element ref="{settings.cobieifc.transform.prairiesky.com}ComponentPropertyNameExclusions" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PropertyExclusionsType", propOrder = {
    "excludePropertiesOnNameEqValue",
    "nameEqValueExceptions",
    "valueExclusions",
    "globalPropertySetNameExclusions",
    "globalPropertyNameExclusions",
    "facilityPropertySetNameExclusions",
    "facilityPropertyNameExclusions",
    "floorPropertySetNameExclusions",
    "floorPropertyNameExclusions",
    "spacePropertySetNameExclusions",
    "spacePropertyNameExclusions",
    "typePropertySetNameExclusions",
    "typePropertyNameExclusions",
    "componentPropertySetNameExclusions",
    "componentPropertyNameExclusions"
})
public class PropertyExclusionsType {

    @XmlElement(name = "ExcludePropertiesOnNameEqValue")
    protected boolean excludePropertiesOnNameEqValue;
    @XmlElement(name = "NameEqValueExceptions")
    protected NameCollectionType nameEqValueExceptions;
    @XmlElement(name = "ValueExclusions")
    protected ValueExclusionCollectionType valueExclusions;
    @XmlElement(name = "GlobalPropertySetNameExclusions")
    protected ValueExclusionCollectionType globalPropertySetNameExclusions;
    @XmlElement(name = "GlobalPropertyNameExclusions")
    protected ValueExclusionCollectionType globalPropertyNameExclusions;
    @XmlElement(name = "FacilityPropertySetNameExclusions")
    protected ValueExclusionCollectionType facilityPropertySetNameExclusions;
    @XmlElement(name = "FacilityPropertyNameExclusions")
    protected ValueExclusionCollectionType facilityPropertyNameExclusions;
    @XmlElement(name = "FloorPropertySetNameExclusions")
    protected ValueExclusionCollectionType floorPropertySetNameExclusions;
    @XmlElement(name = "FloorPropertyNameExclusions")
    protected ValueExclusionCollectionType floorPropertyNameExclusions;
    @XmlElement(name = "SpacePropertySetNameExclusions")
    protected ValueExclusionCollectionType spacePropertySetNameExclusions;
    @XmlElement(name = "SpacePropertyNameExclusions")
    protected ValueExclusionCollectionType spacePropertyNameExclusions;
    @XmlElement(name = "TypePropertySetNameExclusions")
    protected ValueExclusionCollectionType typePropertySetNameExclusions;
    @XmlElement(name = "TypePropertyNameExclusions")
    protected ValueExclusionCollectionType typePropertyNameExclusions;
    @XmlElement(name = "ComponentPropertySetNameExclusions")
    protected ValueExclusionCollectionType componentPropertySetNameExclusions;
    @XmlElement(name = "ComponentPropertyNameExclusions")
    protected ValueExclusionCollectionType componentPropertyNameExclusions;

    /**
     * Gets the value of the excludePropertiesOnNameEqValue property.
     * 
     */
    public boolean isExcludePropertiesOnNameEqValue() {
        return excludePropertiesOnNameEqValue;
    }

    /**
     * Sets the value of the excludePropertiesOnNameEqValue property.
     * 
     */
    public void setExcludePropertiesOnNameEqValue(boolean value) {
        this.excludePropertiesOnNameEqValue = value;
    }

    /**
     * Gets the value of the nameEqValueExceptions property.
     * 
     * @return
     *     possible object is
     *     {@link NameCollectionType }
     *     
     */
    public NameCollectionType getNameEqValueExceptions() {
        return nameEqValueExceptions;
    }

    /**
     * Sets the value of the nameEqValueExceptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameCollectionType }
     *     
     */
    public void setNameEqValueExceptions(NameCollectionType value) {
        this.nameEqValueExceptions = value;
    }

    /**
     * Gets the value of the valueExclusions property.
     * 
     * @return
     *     possible object is
     *     {@link ValueExclusionCollectionType }
     *     
     */
    public ValueExclusionCollectionType getValueExclusions() {
        return valueExclusions;
    }

    /**
     * Sets the value of the valueExclusions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValueExclusionCollectionType }
     *     
     */
    public void setValueExclusions(ValueExclusionCollectionType value) {
        this.valueExclusions = value;
    }

    /**
     * Gets the value of the globalPropertySetNameExclusions property.
     * 
     * @return
     *     possible object is
     *     {@link ValueExclusionCollectionType }
     *     
     */
    public ValueExclusionCollectionType getGlobalPropertySetNameExclusions() {
        return globalPropertySetNameExclusions;
    }

    /**
     * Sets the value of the globalPropertySetNameExclusions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValueExclusionCollectionType }
     *     
     */
    public void setGlobalPropertySetNameExclusions(ValueExclusionCollectionType value) {
        this.globalPropertySetNameExclusions = value;
    }

    /**
     * Gets the value of the globalPropertyNameExclusions property.
     * 
     * @return
     *     possible object is
     *     {@link ValueExclusionCollectionType }
     *     
     */
    public ValueExclusionCollectionType getGlobalPropertyNameExclusions() {
        return globalPropertyNameExclusions;
    }

    /**
     * Sets the value of the globalPropertyNameExclusions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValueExclusionCollectionType }
     *     
     */
    public void setGlobalPropertyNameExclusions(ValueExclusionCollectionType value) {
        this.globalPropertyNameExclusions = value;
    }

    /**
     * Gets the value of the facilityPropertySetNameExclusions property.
     * 
     * @return
     *     possible object is
     *     {@link ValueExclusionCollectionType }
     *     
     */
    public ValueExclusionCollectionType getFacilityPropertySetNameExclusions() {
        return facilityPropertySetNameExclusions;
    }

    /**
     * Sets the value of the facilityPropertySetNameExclusions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValueExclusionCollectionType }
     *     
     */
    public void setFacilityPropertySetNameExclusions(ValueExclusionCollectionType value) {
        this.facilityPropertySetNameExclusions = value;
    }

    /**
     * Gets the value of the facilityPropertyNameExclusions property.
     * 
     * @return
     *     possible object is
     *     {@link ValueExclusionCollectionType }
     *     
     */
    public ValueExclusionCollectionType getFacilityPropertyNameExclusions() {
        return facilityPropertyNameExclusions;
    }

    /**
     * Sets the value of the facilityPropertyNameExclusions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValueExclusionCollectionType }
     *     
     */
    public void setFacilityPropertyNameExclusions(ValueExclusionCollectionType value) {
        this.facilityPropertyNameExclusions = value;
    }

    /**
     * Gets the value of the floorPropertySetNameExclusions property.
     * 
     * @return
     *     possible object is
     *     {@link ValueExclusionCollectionType }
     *     
     */
    public ValueExclusionCollectionType getFloorPropertySetNameExclusions() {
        return floorPropertySetNameExclusions;
    }

    /**
     * Sets the value of the floorPropertySetNameExclusions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValueExclusionCollectionType }
     *     
     */
    public void setFloorPropertySetNameExclusions(ValueExclusionCollectionType value) {
        this.floorPropertySetNameExclusions = value;
    }

    /**
     * Gets the value of the floorPropertyNameExclusions property.
     * 
     * @return
     *     possible object is
     *     {@link ValueExclusionCollectionType }
     *     
     */
    public ValueExclusionCollectionType getFloorPropertyNameExclusions() {
        return floorPropertyNameExclusions;
    }

    /**
     * Sets the value of the floorPropertyNameExclusions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValueExclusionCollectionType }
     *     
     */
    public void setFloorPropertyNameExclusions(ValueExclusionCollectionType value) {
        this.floorPropertyNameExclusions = value;
    }

    /**
     * Gets the value of the spacePropertySetNameExclusions property.
     * 
     * @return
     *     possible object is
     *     {@link ValueExclusionCollectionType }
     *     
     */
    public ValueExclusionCollectionType getSpacePropertySetNameExclusions() {
        return spacePropertySetNameExclusions;
    }

    /**
     * Sets the value of the spacePropertySetNameExclusions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValueExclusionCollectionType }
     *     
     */
    public void setSpacePropertySetNameExclusions(ValueExclusionCollectionType value) {
        this.spacePropertySetNameExclusions = value;
    }

    /**
     * Gets the value of the spacePropertyNameExclusions property.
     * 
     * @return
     *     possible object is
     *     {@link ValueExclusionCollectionType }
     *     
     */
    public ValueExclusionCollectionType getSpacePropertyNameExclusions() {
        return spacePropertyNameExclusions;
    }

    /**
     * Sets the value of the spacePropertyNameExclusions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValueExclusionCollectionType }
     *     
     */
    public void setSpacePropertyNameExclusions(ValueExclusionCollectionType value) {
        this.spacePropertyNameExclusions = value;
    }

    /**
     * Gets the value of the typePropertySetNameExclusions property.
     * 
     * @return
     *     possible object is
     *     {@link ValueExclusionCollectionType }
     *     
     */
    public ValueExclusionCollectionType getTypePropertySetNameExclusions() {
        return typePropertySetNameExclusions;
    }

    /**
     * Sets the value of the typePropertySetNameExclusions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValueExclusionCollectionType }
     *     
     */
    public void setTypePropertySetNameExclusions(ValueExclusionCollectionType value) {
        this.typePropertySetNameExclusions = value;
    }

    /**
     * Gets the value of the typePropertyNameExclusions property.
     * 
     * @return
     *     possible object is
     *     {@link ValueExclusionCollectionType }
     *     
     */
    public ValueExclusionCollectionType getTypePropertyNameExclusions() {
        return typePropertyNameExclusions;
    }

    /**
     * Sets the value of the typePropertyNameExclusions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValueExclusionCollectionType }
     *     
     */
    public void setTypePropertyNameExclusions(ValueExclusionCollectionType value) {
        this.typePropertyNameExclusions = value;
    }

    /**
     * Gets the value of the componentPropertySetNameExclusions property.
     * 
     * @return
     *     possible object is
     *     {@link ValueExclusionCollectionType }
     *     
     */
    public ValueExclusionCollectionType getComponentPropertySetNameExclusions() {
        return componentPropertySetNameExclusions;
    }

    /**
     * Sets the value of the componentPropertySetNameExclusions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValueExclusionCollectionType }
     *     
     */
    public void setComponentPropertySetNameExclusions(ValueExclusionCollectionType value) {
        this.componentPropertySetNameExclusions = value;
    }

    /**
     * Gets the value of the componentPropertyNameExclusions property.
     * 
     * @return
     *     possible object is
     *     {@link ValueExclusionCollectionType }
     *     
     */
    public ValueExclusionCollectionType getComponentPropertyNameExclusions() {
        return componentPropertyNameExclusions;
    }

    /**
     * Sets the value of the componentPropertyNameExclusions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValueExclusionCollectionType }
     *     
     */
    public void setComponentPropertyNameExclusions(ValueExclusionCollectionType value) {
        this.componentPropertyNameExclusions = value;
    }

}
