//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 11:29:24 AM PDT 
//


package com.prairiesky.transform.cobieifc.settings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TypeSettingsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TypeSettingsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{settings.cobieifc.transform.prairiesky.com}IfcTypeExclusions"/>
 *         &lt;element ref="{settings.cobieifc.transform.prairiesky.com}AssetTypePropertyNames"/>
 *         &lt;element ref="{settings.cobieifc.transform.prairiesky.com}ManufacturerPropertyNames"/>
 *         &lt;element ref="{settings.cobieifc.transform.prairiesky.com}ModelNumberPropertyNames"/>
 *         &lt;element ref="{settings.cobieifc.transform.prairiesky.com}WarrantyGuarantorPartsPropertyNames"/>
 *         &lt;element ref="{settings.cobieifc.transform.prairiesky.com}WarrantyDurationPartsPropertyNames"/>
 *         &lt;element ref="{settings.cobieifc.transform.prairiesky.com}WarrantyGuarantorLaborPropertyNames"/>
 *         &lt;element ref="{settings.cobieifc.transform.prairiesky.com}WarrantyDurationLaborPropertyNames"/>
 *         &lt;element ref="{settings.cobieifc.transform.prairiesky.com}ReplacementCostPropertyNames"/>
 *         &lt;element ref="{settings.cobieifc.transform.prairiesky.com}ExpectedLifePropertyNames"/>
 *         &lt;element ref="{settings.cobieifc.transform.prairiesky.com}WarrantyDescriptionPropertyNames"/>
 *         &lt;element ref="{settings.cobieifc.transform.prairiesky.com}NominalLengthPropertyNames"/>
 *         &lt;element ref="{settings.cobieifc.transform.prairiesky.com}NominalWidthPropertyNames"/>
 *         &lt;element ref="{settings.cobieifc.transform.prairiesky.com}NominalHeightPropertyNames"/>
 *         &lt;element ref="{settings.cobieifc.transform.prairiesky.com}ModelReferencePropertyNames"/>
 *         &lt;element ref="{settings.cobieifc.transform.prairiesky.com}ShapePropertyNames"/>
 *         &lt;element ref="{settings.cobieifc.transform.prairiesky.com}SizePropertyNames"/>
 *         &lt;element ref="{settings.cobieifc.transform.prairiesky.com}ColorPropertyNames"/>
 *         &lt;element ref="{settings.cobieifc.transform.prairiesky.com}FinishPropertyNames"/>
 *         &lt;element ref="{settings.cobieifc.transform.prairiesky.com}GradePropertyNames"/>
 *         &lt;element ref="{settings.cobieifc.transform.prairiesky.com}MaterialPropertyNames"/>
 *         &lt;element ref="{settings.cobieifc.transform.prairiesky.com}ConstituentsPropertyNames"/>
 *         &lt;element ref="{settings.cobieifc.transform.prairiesky.com}FeaturesPropertyNames"/>
 *         &lt;element ref="{settings.cobieifc.transform.prairiesky.com}AccessibilityPerformancePropertyNames"/>
 *         &lt;element ref="{settings.cobieifc.transform.prairiesky.com}CodePerformancePropertyNames"/>
 *         &lt;element ref="{settings.cobieifc.transform.prairiesky.com}SustainabilityPerformancePropertyNames"/>
 *         &lt;element ref="{settings.cobieifc.transform.prairiesky.com}DefaultWarrantyDurationUnit"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TypeSettingsType", propOrder = {
    "ifcTypeExclusions",
    "assetTypePropertyNames",
    "manufacturerPropertyNames",
    "modelNumberPropertyNames",
    "warrantyGuarantorPartsPropertyNames",
    "warrantyDurationPartsPropertyNames",
    "warrantyGuarantorLaborPropertyNames",
    "warrantyDurationLaborPropertyNames",
    "replacementCostPropertyNames",
    "expectedLifePropertyNames",
    "warrantyDescriptionPropertyNames",
    "nominalLengthPropertyNames",
    "nominalWidthPropertyNames",
    "nominalHeightPropertyNames",
    "modelReferencePropertyNames",
    "shapePropertyNames",
    "sizePropertyNames",
    "colorPropertyNames",
    "finishPropertyNames",
    "gradePropertyNames",
    "materialPropertyNames",
    "constituentsPropertyNames",
    "featuresPropertyNames",
    "accessibilityPerformancePropertyNames",
    "codePerformancePropertyNames",
    "sustainabilityPerformancePropertyNames",
    "defaultWarrantyDurationUnit"
})
public class TypeSettingsType {

    @XmlElement(name = "IfcTypeExclusions", required = true)
    protected NameCollectionType ifcTypeExclusions;
    @XmlElement(name = "AssetTypePropertyNames", required = true)
    protected NameCollectionType assetTypePropertyNames;
    @XmlElement(name = "ManufacturerPropertyNames", required = true)
    protected NameCollectionType manufacturerPropertyNames;
    @XmlElement(name = "ModelNumberPropertyNames", required = true)
    protected NameCollectionType modelNumberPropertyNames;
    @XmlElement(name = "WarrantyGuarantorPartsPropertyNames", required = true)
    protected NameCollectionType warrantyGuarantorPartsPropertyNames;
    @XmlElement(name = "WarrantyDurationPartsPropertyNames", required = true)
    protected NameCollectionType warrantyDurationPartsPropertyNames;
    @XmlElement(name = "WarrantyGuarantorLaborPropertyNames", required = true)
    protected NameCollectionType warrantyGuarantorLaborPropertyNames;
    @XmlElement(name = "WarrantyDurationLaborPropertyNames", required = true)
    protected NameCollectionType warrantyDurationLaborPropertyNames;
    @XmlElement(name = "ReplacementCostPropertyNames", required = true)
    protected NameCollectionType replacementCostPropertyNames;
    @XmlElement(name = "ExpectedLifePropertyNames", required = true)
    protected NameCollectionType expectedLifePropertyNames;
    @XmlElement(name = "WarrantyDescriptionPropertyNames", required = true)
    protected NameCollectionType warrantyDescriptionPropertyNames;
    @XmlElement(name = "NominalLengthPropertyNames", required = true)
    protected NameCollectionType nominalLengthPropertyNames;
    @XmlElement(name = "NominalWidthPropertyNames", required = true)
    protected NameCollectionType nominalWidthPropertyNames;
    @XmlElement(name = "NominalHeightPropertyNames", required = true)
    protected NameCollectionType nominalHeightPropertyNames;
    @XmlElement(name = "ModelReferencePropertyNames", required = true)
    protected NameCollectionType modelReferencePropertyNames;
    @XmlElement(name = "ShapePropertyNames", required = true)
    protected NameCollectionType shapePropertyNames;
    @XmlElement(name = "SizePropertyNames", required = true)
    protected NameCollectionType sizePropertyNames;
    @XmlElement(name = "ColorPropertyNames", required = true)
    protected NameCollectionType colorPropertyNames;
    @XmlElement(name = "FinishPropertyNames", required = true)
    protected NameCollectionType finishPropertyNames;
    @XmlElement(name = "GradePropertyNames", required = true)
    protected NameCollectionType gradePropertyNames;
    @XmlElement(name = "MaterialPropertyNames", required = true)
    protected NameCollectionType materialPropertyNames;
    @XmlElement(name = "ConstituentsPropertyNames", required = true)
    protected NameCollectionType constituentsPropertyNames;
    @XmlElement(name = "FeaturesPropertyNames", required = true)
    protected NameCollectionType featuresPropertyNames;
    @XmlElement(name = "AccessibilityPerformancePropertyNames", required = true)
    protected NameCollectionType accessibilityPerformancePropertyNames;
    @XmlElement(name = "CodePerformancePropertyNames", required = true)
    protected NameCollectionType codePerformancePropertyNames;
    @XmlElement(name = "SustainabilityPerformancePropertyNames", required = true)
    protected NameCollectionType sustainabilityPerformancePropertyNames;
    @XmlElement(name = "DefaultWarrantyDurationUnit", required = true)
    protected String defaultWarrantyDurationUnit;

    /**
     * Gets the value of the ifcTypeExclusions property.
     * 
     * @return
     *     possible object is
     *     {@link NameCollectionType }
     *     
     */
    public NameCollectionType getIfcTypeExclusions() {
        return ifcTypeExclusions;
    }

    /**
     * Sets the value of the ifcTypeExclusions property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameCollectionType }
     *     
     */
    public void setIfcTypeExclusions(NameCollectionType value) {
        this.ifcTypeExclusions = value;
    }

    /**
     * Gets the value of the assetTypePropertyNames property.
     * 
     * @return
     *     possible object is
     *     {@link NameCollectionType }
     *     
     */
    public NameCollectionType getAssetTypePropertyNames() {
        return assetTypePropertyNames;
    }

    /**
     * Sets the value of the assetTypePropertyNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameCollectionType }
     *     
     */
    public void setAssetTypePropertyNames(NameCollectionType value) {
        this.assetTypePropertyNames = value;
    }

    /**
     * Gets the value of the manufacturerPropertyNames property.
     * 
     * @return
     *     possible object is
     *     {@link NameCollectionType }
     *     
     */
    public NameCollectionType getManufacturerPropertyNames() {
        return manufacturerPropertyNames;
    }

    /**
     * Sets the value of the manufacturerPropertyNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameCollectionType }
     *     
     */
    public void setManufacturerPropertyNames(NameCollectionType value) {
        this.manufacturerPropertyNames = value;
    }

    /**
     * Gets the value of the modelNumberPropertyNames property.
     * 
     * @return
     *     possible object is
     *     {@link NameCollectionType }
     *     
     */
    public NameCollectionType getModelNumberPropertyNames() {
        return modelNumberPropertyNames;
    }

    /**
     * Sets the value of the modelNumberPropertyNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameCollectionType }
     *     
     */
    public void setModelNumberPropertyNames(NameCollectionType value) {
        this.modelNumberPropertyNames = value;
    }

    /**
     * Gets the value of the warrantyGuarantorPartsPropertyNames property.
     * 
     * @return
     *     possible object is
     *     {@link NameCollectionType }
     *     
     */
    public NameCollectionType getWarrantyGuarantorPartsPropertyNames() {
        return warrantyGuarantorPartsPropertyNames;
    }

    /**
     * Sets the value of the warrantyGuarantorPartsPropertyNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameCollectionType }
     *     
     */
    public void setWarrantyGuarantorPartsPropertyNames(NameCollectionType value) {
        this.warrantyGuarantorPartsPropertyNames = value;
    }

    /**
     * Gets the value of the warrantyDurationPartsPropertyNames property.
     * 
     * @return
     *     possible object is
     *     {@link NameCollectionType }
     *     
     */
    public NameCollectionType getWarrantyDurationPartsPropertyNames() {
        return warrantyDurationPartsPropertyNames;
    }

    /**
     * Sets the value of the warrantyDurationPartsPropertyNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameCollectionType }
     *     
     */
    public void setWarrantyDurationPartsPropertyNames(NameCollectionType value) {
        this.warrantyDurationPartsPropertyNames = value;
    }

    /**
     * Gets the value of the warrantyGuarantorLaborPropertyNames property.
     * 
     * @return
     *     possible object is
     *     {@link NameCollectionType }
     *     
     */
    public NameCollectionType getWarrantyGuarantorLaborPropertyNames() {
        return warrantyGuarantorLaborPropertyNames;
    }

    /**
     * Sets the value of the warrantyGuarantorLaborPropertyNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameCollectionType }
     *     
     */
    public void setWarrantyGuarantorLaborPropertyNames(NameCollectionType value) {
        this.warrantyGuarantorLaborPropertyNames = value;
    }

    /**
     * Gets the value of the warrantyDurationLaborPropertyNames property.
     * 
     * @return
     *     possible object is
     *     {@link NameCollectionType }
     *     
     */
    public NameCollectionType getWarrantyDurationLaborPropertyNames() {
        return warrantyDurationLaborPropertyNames;
    }

    /**
     * Sets the value of the warrantyDurationLaborPropertyNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameCollectionType }
     *     
     */
    public void setWarrantyDurationLaborPropertyNames(NameCollectionType value) {
        this.warrantyDurationLaborPropertyNames = value;
    }

    /**
     * Gets the value of the replacementCostPropertyNames property.
     * 
     * @return
     *     possible object is
     *     {@link NameCollectionType }
     *     
     */
    public NameCollectionType getReplacementCostPropertyNames() {
        return replacementCostPropertyNames;
    }

    /**
     * Sets the value of the replacementCostPropertyNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameCollectionType }
     *     
     */
    public void setReplacementCostPropertyNames(NameCollectionType value) {
        this.replacementCostPropertyNames = value;
    }

    /**
     * Gets the value of the expectedLifePropertyNames property.
     * 
     * @return
     *     possible object is
     *     {@link NameCollectionType }
     *     
     */
    public NameCollectionType getExpectedLifePropertyNames() {
        return expectedLifePropertyNames;
    }

    /**
     * Sets the value of the expectedLifePropertyNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameCollectionType }
     *     
     */
    public void setExpectedLifePropertyNames(NameCollectionType value) {
        this.expectedLifePropertyNames = value;
    }

    /**
     * Gets the value of the warrantyDescriptionPropertyNames property.
     * 
     * @return
     *     possible object is
     *     {@link NameCollectionType }
     *     
     */
    public NameCollectionType getWarrantyDescriptionPropertyNames() {
        return warrantyDescriptionPropertyNames;
    }

    /**
     * Sets the value of the warrantyDescriptionPropertyNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameCollectionType }
     *     
     */
    public void setWarrantyDescriptionPropertyNames(NameCollectionType value) {
        this.warrantyDescriptionPropertyNames = value;
    }

    /**
     * Gets the value of the nominalLengthPropertyNames property.
     * 
     * @return
     *     possible object is
     *     {@link NameCollectionType }
     *     
     */
    public NameCollectionType getNominalLengthPropertyNames() {
        return nominalLengthPropertyNames;
    }

    /**
     * Sets the value of the nominalLengthPropertyNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameCollectionType }
     *     
     */
    public void setNominalLengthPropertyNames(NameCollectionType value) {
        this.nominalLengthPropertyNames = value;
    }

    /**
     * Gets the value of the nominalWidthPropertyNames property.
     * 
     * @return
     *     possible object is
     *     {@link NameCollectionType }
     *     
     */
    public NameCollectionType getNominalWidthPropertyNames() {
        return nominalWidthPropertyNames;
    }

    /**
     * Sets the value of the nominalWidthPropertyNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameCollectionType }
     *     
     */
    public void setNominalWidthPropertyNames(NameCollectionType value) {
        this.nominalWidthPropertyNames = value;
    }

    /**
     * Gets the value of the nominalHeightPropertyNames property.
     * 
     * @return
     *     possible object is
     *     {@link NameCollectionType }
     *     
     */
    public NameCollectionType getNominalHeightPropertyNames() {
        return nominalHeightPropertyNames;
    }

    /**
     * Sets the value of the nominalHeightPropertyNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameCollectionType }
     *     
     */
    public void setNominalHeightPropertyNames(NameCollectionType value) {
        this.nominalHeightPropertyNames = value;
    }

    /**
     * Gets the value of the modelReferencePropertyNames property.
     * 
     * @return
     *     possible object is
     *     {@link NameCollectionType }
     *     
     */
    public NameCollectionType getModelReferencePropertyNames() {
        return modelReferencePropertyNames;
    }

    /**
     * Sets the value of the modelReferencePropertyNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameCollectionType }
     *     
     */
    public void setModelReferencePropertyNames(NameCollectionType value) {
        this.modelReferencePropertyNames = value;
    }

    /**
     * Gets the value of the shapePropertyNames property.
     * 
     * @return
     *     possible object is
     *     {@link NameCollectionType }
     *     
     */
    public NameCollectionType getShapePropertyNames() {
        return shapePropertyNames;
    }

    /**
     * Sets the value of the shapePropertyNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameCollectionType }
     *     
     */
    public void setShapePropertyNames(NameCollectionType value) {
        this.shapePropertyNames = value;
    }

    /**
     * Gets the value of the sizePropertyNames property.
     * 
     * @return
     *     possible object is
     *     {@link NameCollectionType }
     *     
     */
    public NameCollectionType getSizePropertyNames() {
        return sizePropertyNames;
    }

    /**
     * Sets the value of the sizePropertyNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameCollectionType }
     *     
     */
    public void setSizePropertyNames(NameCollectionType value) {
        this.sizePropertyNames = value;
    }

    /**
     * Gets the value of the colorPropertyNames property.
     * 
     * @return
     *     possible object is
     *     {@link NameCollectionType }
     *     
     */
    public NameCollectionType getColorPropertyNames() {
        return colorPropertyNames;
    }

    /**
     * Sets the value of the colorPropertyNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameCollectionType }
     *     
     */
    public void setColorPropertyNames(NameCollectionType value) {
        this.colorPropertyNames = value;
    }

    /**
     * Gets the value of the finishPropertyNames property.
     * 
     * @return
     *     possible object is
     *     {@link NameCollectionType }
     *     
     */
    public NameCollectionType getFinishPropertyNames() {
        return finishPropertyNames;
    }

    /**
     * Sets the value of the finishPropertyNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameCollectionType }
     *     
     */
    public void setFinishPropertyNames(NameCollectionType value) {
        this.finishPropertyNames = value;
    }

    /**
     * Gets the value of the gradePropertyNames property.
     * 
     * @return
     *     possible object is
     *     {@link NameCollectionType }
     *     
     */
    public NameCollectionType getGradePropertyNames() {
        return gradePropertyNames;
    }

    /**
     * Sets the value of the gradePropertyNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameCollectionType }
     *     
     */
    public void setGradePropertyNames(NameCollectionType value) {
        this.gradePropertyNames = value;
    }

    /**
     * Gets the value of the materialPropertyNames property.
     * 
     * @return
     *     possible object is
     *     {@link NameCollectionType }
     *     
     */
    public NameCollectionType getMaterialPropertyNames() {
        return materialPropertyNames;
    }

    /**
     * Sets the value of the materialPropertyNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameCollectionType }
     *     
     */
    public void setMaterialPropertyNames(NameCollectionType value) {
        this.materialPropertyNames = value;
    }

    /**
     * Gets the value of the constituentsPropertyNames property.
     * 
     * @return
     *     possible object is
     *     {@link NameCollectionType }
     *     
     */
    public NameCollectionType getConstituentsPropertyNames() {
        return constituentsPropertyNames;
    }

    /**
     * Sets the value of the constituentsPropertyNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameCollectionType }
     *     
     */
    public void setConstituentsPropertyNames(NameCollectionType value) {
        this.constituentsPropertyNames = value;
    }

    /**
     * Gets the value of the featuresPropertyNames property.
     * 
     * @return
     *     possible object is
     *     {@link NameCollectionType }
     *     
     */
    public NameCollectionType getFeaturesPropertyNames() {
        return featuresPropertyNames;
    }

    /**
     * Sets the value of the featuresPropertyNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameCollectionType }
     *     
     */
    public void setFeaturesPropertyNames(NameCollectionType value) {
        this.featuresPropertyNames = value;
    }

    /**
     * Gets the value of the accessibilityPerformancePropertyNames property.
     * 
     * @return
     *     possible object is
     *     {@link NameCollectionType }
     *     
     */
    public NameCollectionType getAccessibilityPerformancePropertyNames() {
        return accessibilityPerformancePropertyNames;
    }

    /**
     * Sets the value of the accessibilityPerformancePropertyNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameCollectionType }
     *     
     */
    public void setAccessibilityPerformancePropertyNames(NameCollectionType value) {
        this.accessibilityPerformancePropertyNames = value;
    }

    /**
     * Gets the value of the codePerformancePropertyNames property.
     * 
     * @return
     *     possible object is
     *     {@link NameCollectionType }
     *     
     */
    public NameCollectionType getCodePerformancePropertyNames() {
        return codePerformancePropertyNames;
    }

    /**
     * Sets the value of the codePerformancePropertyNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameCollectionType }
     *     
     */
    public void setCodePerformancePropertyNames(NameCollectionType value) {
        this.codePerformancePropertyNames = value;
    }

    /**
     * Gets the value of the sustainabilityPerformancePropertyNames property.
     * 
     * @return
     *     possible object is
     *     {@link NameCollectionType }
     *     
     */
    public NameCollectionType getSustainabilityPerformancePropertyNames() {
        return sustainabilityPerformancePropertyNames;
    }

    /**
     * Sets the value of the sustainabilityPerformancePropertyNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameCollectionType }
     *     
     */
    public void setSustainabilityPerformancePropertyNames(NameCollectionType value) {
        this.sustainabilityPerformancePropertyNames = value;
    }

    /**
     * Gets the value of the defaultWarrantyDurationUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultWarrantyDurationUnit() {
        return defaultWarrantyDurationUnit;
    }

    /**
     * Sets the value of the defaultWarrantyDurationUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultWarrantyDurationUnit(String value) {
        this.defaultWarrantyDurationUnit = value;
    }

}
