package org.bimserver.cobie.shared.transform.spreadsheetml.cobietab;
/******************************************************************************

 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *****************************************************************************/
///This Class was written to provide the text to inject into spreadsheetML text generated by the xelem library
///xelem does not import or export the DataValidation element, and they must be manually inserted.
///So, this class provides strings containing the DataValidation elements for each COBie spreadsheet.
public class COBieSpreadsheetOptions 
{
	public static final String contactDataValidationElementText =
			"<DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C4:R9999C4</Range>"+
					"   <Type>List</Type>"+
					"   <Value>Table34</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C8:R9999C8</Range>"+
					"   <Type>List</Type>"+
					"   <Value>objContact</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C2:R9999C2</Range>"+
					"   <Type>List</Type>"+
					"   <Value>Contact.Name</Value>"+
					"  </DataValidation>";
	
	public static final String facilityDataValidationElementText =
			"<DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C13:R9999C13</Range>"+
					"   <Type>List</Type>"+
					"   <Value>objProject</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C15:R9999C15</Range>"+
					"   <Type>List</Type>"+
					"   <Value>objSite</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C17:R9999C17</Range>"+
					"   <Type>List</Type>"+
					"   <Value>objFacility</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C4:R9999C4</Range>"+
					"   <Type>List</Type>"+
					"   <Value>Table11</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C2:R9999C2</Range>"+
					"   <Type>List</Type>"+
					"   <Value>Contact.Name</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C7:R9999C7</Range>"+
					"   <Type>List</Type>"+
					"   <Value>LengthUnit</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C8:R9999C8</Range>"+
					"   <Type>List</Type>"+
					"   <Value>AreaUnit</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C9:R9999C9</Range>"+
					"   <Type>List</Type>"+
					"   <Value>VolumeUnit</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C10:R9999C10</Range>"+
					"   <Type>List</Type>"+
					"   <Value>CostUnit</Value>"+
					"  </DataValidation>";
	
	public static final String floorDataValidationElementText =
			"<DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C6:R9999C6</Range>"+
					"   <Type>List</Type>"+
					"   <Value>objFloor</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C4:R9999C4</Range>"+
					"   <Type>List</Type>"+
					"   <Value>FloorType</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C2:R9999C2</Range>"+
					"   <Type>List</Type>"+
					"   <Value>Contact.Name</Value>"+
					"  </DataValidation>";
	
	public static final String spaceDataValidationElementText =
			"<DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C4:R9999C4</Range>"+
					"   <Type>List</Type>"+
					"   <Value>Table13</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C5:R9999C5</Range>"+
					"   <Type>List</Type>"+
					"   <Value>Floor.Name</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C8:R9999C8</Range>"+
					"   <Type>List</Type>"+
					"   <Value>objSpace</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C2:R9999C2</Range>"+
					"   <Type>List</Type>"+
					"   <Value>Contact.Name</Value>"+
					"  </DataValidation>";
	
	public static final String zoneDataValidationElementText =
			"<DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C7:R9999C7</Range>"+
					"   <Type>List</Type>"+
					"   <Value>objZone</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C5:R9999C5</Range>"+
					"   <Type>List</Type>"+
					"   <Value>Space.Name</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C4:R9999C4</Range>"+
					"   <Type>List</Type>"+
					"   <Value>ZoneType</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C2:R9999C2</Range>"+
					"   <Type>List</Type>"+
					"   <Value>Contact.Name</Value>"+
					"  </DataValidation>";
	
	public static final String typeDataValidationElementText =
			"<DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C15:R9999C15</Range>"+
					"   <Type>List</Type>"+
					"   <Value>objType</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C19:R9999C19</Range>"+
					"   <Type>List</Type>"+
					"   <Value>DurationUnit</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C11:R9999C11,R2C7:R9999C7,R2C9:R9999C9</Range>"+
					"   <Type>List</Type>"+
					"   <Value>Contact.Name</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C6:R9999C6</Range>"+
					"   <Type>List</Type>"+
					"   <Value>AssetType</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C4:R9999C4</Range>"+
					"   <Type>List</Type>"+
					"   <Value>Table23</Value>"+
					"  </DataValidation>";
	public static final String componentDataValidationElementText =
			"<DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C4:R9999C4</Range>"+
					"   <Type>List</Type>"+
					"   <Value>Type.Name</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C8:R9999C8</Range>"+
					"   <Type>List</Type>"+
					"   <Value>objComponent</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C5:R9999C5</Range>"+
					"   <Type>List</Type>"+
					"   <Value>Space.Name</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C2:R9999C2</Range>"+
					"   <Type>List</Type>"+
					"   <Value>Contact.Name</Value>"+
					"  </DataValidation>";
	
	public static final String systemDataValidationElementText =
			" <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C7:R9999C7</Range>"+
					"   <Type>List</Type>"+
					"   <Value>objSystem</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C5:R9999C5</Range>"+
					"   <Type>List</Type>"+
					"   <Value>Component.Name</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C4:R9999C4</Range>"+
					"   <Type>List</Type>"+
					"   <Value>Table21</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C2:R9999C2</Range>"+
					"   <Type>List</Type>"+
					"   <Value>Contact.Name</Value>"+
					"  </DataValidation>";
	
	public static final String assemblyDataValidationElementText =
			" <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C9:R9999C9</Range>"+
					"   <Type>List</Type>"+
					"   <Value>objAssembly</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C4:R9999C4</Range>"+
					"   <Type>List</Type>"+
					"   <Value>SheetType</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C7:R9999C7</Range>"+
					"   <Type>List</Type>"+
					"   <Value>AssemblyType</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C2:R9999C2</Range>"+
					"   <Type>List</Type>"+
					"   <Value>Contact.Name</Value>"+
					"  </DataValidation>";
	
	public static final String connectionDataValidationElementText =
			"<DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C4:R9999C4</Range>"+
					"   <Type>List</Type>"+
					"   <Value>ConnectionType</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C5:R9999C5</Range>"+
					"   <Type>List</Type>"+
					"   <Value>SheetName</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C9:R9999C9,R2C10:R9999C10</Range>"+
					"   <Type>List</Type>"+
					"   <Value>Connection.Name</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C2:R9999C2</Range>"+
					"   <Type>List</Type>"+
					"   <Value>Contact.Name</Value>"+
					"  </DataValidation>";
	
	public static final String spareDataValidationElementText =
			"<DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C6:R9999C6</Range>"+
					"   <Type>List</Type>"+
					"   <Value>Contact.Name</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C8:R9999C8</Range>"+
					"   <Type>List</Type>"+
					"   <Value>objSpare</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C4:R9999C4</Range>"+
					"   <Type>List</Type>"+
					"   <Value>SpareType</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C5:R9999C5</Range>"+
					"   <Type>List</Type>"+
					"   <Value>Type.Name</Value>"+
					"  </DataValidation>";
	
	public static final String resourceDataValidationElementText =
			"<DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C4:R9999C4</Range>"+
					"   <Type>List</Type>"+
					"   <Value>ResourceType</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C6:R9999C6</Range>"+
					"   <Type>List</Type>"+
					"   <CellRangeList/>"+
					"   <Value>&quot;objResource&quot;</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C2:R9999C2</Range>"+
					"   <Type>List</Type>"+
					"   <Value>Contact.Name</Value>"+
					"  </DataValidation>";
	
	public static final String jobDataValidationElementText =
			"<DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C9:R9999C9,R2C13:R9999C13</Range>"+
					"   <Type>List</Type>"+
					"   <Value>DurationUnit</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C5:R9999C5</Range>"+
					"   <Type>List</Type>"+
					"   <Value>JobStatusType</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C4:R9999C4</Range>"+
					"   <Type>List</Type>"+
					"   <Value>JobType</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C6:R9999C6</Range>"+
					"   <Type>List</Type>"+
					"   <Value>Type.Name</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C15:R9999C15</Range>"+
					"   <Type>List</Type>"+
					"   <Value>objJob</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C2:R9999C2</Range>"+
					"   <Type>List</Type>"+
					"   <Value>Contact.Name</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C18:R9999C18</Range>"+
					"   <Type>List</Type>"+
					"   <Value>Job.Name</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C19:R9999C19</Range>"+
					"   <Type>List</Type>"+
					"   <Value>Resource.Name</Value>"+
					"  </DataValidation>";
	
	public static final String impactDataValidationElementText =
			"<DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C14:R9999C14</Range>"+
					"   <Type>List</Type>"+
					"   <Value>objImpact</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C4:R9999C4</Range>"+
					"   <Type>List</Type>"+
					"   <Value>ImpactType</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C5:R9999C5</Range>"+
					"   <Type>List</Type>"+
					"   <Value>ImpactStage</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C6:R9999C6</Range>"+
					"   <Type>List</Type>"+
					"   <Value>SheetType</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C9:R9999C9</Range>"+
					"   <Type>List</Type>"+
					"   <Value>ImpactUnit</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C2:R9999C2</Range>"+
					"   <Type>List</Type>"+
					"   <Value>Contact.Name</Value>"+
					"  </DataValidation>";
	
	public static final String documentDataValidationElementText =
			"<DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C5:R9999C5</Range>"+
					"   <Type>List</Type>"+
					"   <Value>ApprovalBy</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C12:R9999C12</Range>"+
					"   <Type>List</Type>"+
					"   <Value>objDocument</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C4:R9999C4</Range>"+
					"   <Type>List</Type>"+
					"   <Value>DocumentType</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C7:R9999C7</Range>"+
					"   <Type>List</Type>"+
					"   <Value>SheetType</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C2:R9999C2</Range>"+
					"   <Type>List</Type>"+
					"   <Value>Contact.Name</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C6:R9999C6</Range>"+
					"   <Type>List</Type>"+
					"   <Value>StageType</Value>"+
					"  </DataValidation>";
	
	public static final String attributeDataValidationElementText =
			"<DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C10:R9999C10</Range>"+
					"   <Type>List</Type>"+
					"   <Value>objAttribute</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C5:R9999C5</Range>"+
					"   <Type>List</Type>"+
					"   <Value>SheetType</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C4:R9999C4</Range>"+
					"   <Type>List</Type>"+
					"   <Value>StageType</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C2:R9999C2</Range>"+
					"   <Type>List</Type>"+
					"   <Value>Contact.Name</Value>"+
					"  </DataValidation>";
	
	public static final String coordinateDataValidationElementText =
			"<DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C4:R9999C4</Range>"+
					"   <Type>List</Type>"+
					"   <Value>CoordinateType</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C11:R9999C11</Range>"+
					"   <Type>List</Type>"+
					"   <Value>objCoordinate</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C5:R9999C5</Range>"+
					"   <Type>List</Type>"+
					"   <Value>SheetType</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C2:R9999C2</Range>"+
					"   <Type>List</Type>"+
					"   <Value>Contact.Name</Value>"+
					"  </DataValidation>";
	
	public static final String issueDataValidationElementText =
			"<DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C13:R9999C13</Range>"+
					"   <Type>List</Type>"+
					"   <Value>Contact.Name</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C4:R9999C4</Range>"+
					"   <Type>List</Type>"+
					"   <Value>IssueCategory</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C5:R9999C5</Range>"+
					"   <Type>List</Type>"+
					"   <Value>IssueRisk</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C6:R9999C6</Range>"+
					"   <Type>List</Type>"+
					"   <Value>IssueChance</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C7:R9999C7</Range>"+
					"   <Type>List</Type>"+
					"   <Value>IssueImpact</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C16:R9999C16</Range>"+
					"   <Type>List</Type>"+
					"   <Value>objIssue</Value>"+
					"  </DataValidation>"+
					"  <DataValidation xmlns=\"urn:schemas-microsoft-com:office:excel\">"+
					"   <Range>R2C8:R9999C8</Range>"+
					"   <Type>List</Type>"+
					"   <Value>SheetType</Value>"+
					"  </DataValidation>";
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	




}
